In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('./data/gemstone.csv')
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   1   0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66    499
1   2   0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70    984
2   3   0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78   6289
3   4   0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96   1082
4   5   0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65    779

In [10]:
df = df.drop(labels=['id'],axis=1)
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66    499
1   0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70    984
2   0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78   6289
3   0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96   1082
4   0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65    779

In [11]:
# dropping independent and dependent features...
X= df.drop(labels=['price'],axis=1)
Y = df[['price']]

In [12]:
#define which columns shoud be ordinal-ecoded and which should be scaled...
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [14]:
#define the custom rranking for each ordinal variable
cut_categories = ['Fair','Good','Veru Good','Premium','Ideal']
color_categories = ['D','E','F','G','H','I','J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [17]:
from sklearn.impute import SimpleImputer #handling missing values
from sklearn.preprocessing import StandardScaler #handing feature scaling
from sklearn.preprocessing import OrdinalEncoder # ordinal encoding...
#from sklearn.preprocessing import OneHotEncoder # ordinal encoding...
##pipelines..
from sklearn.pipeline import pipeline
from sklearn.compose import ColumnTransformer

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
## Numerical Pipeline..